feature:
 - head-branch: ['^feature', 'feature']

new-route:
 - changed-files:
    - any-glob-to-any-file: [src/routes/*]

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
