feature:
 - head-branch: ['^feature', 'feature']

# New Routes
new-route:
 - changed-files:
    - any-glob-to-any-file: [src/routes/*]

#bugfix branches
bugfix:
  - head-branch: ['^bugfix', 'bugfix']
  - changed-files:
    - any-glob-to-any-file: [src/*]

# Add 'release' label to any PR that is opened against the `main` branch
release:
 - base-branch: 'main'
