version = 1

test_patterns = ["*/tests/**"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "mongo"
  ]

[[transformers]]
name = "prettier"
