version = 1

test_patterns = ["*/tests/**"]

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

    [analyzers.meta]
    environment = ["nodejs", "jest","mongodb"]
    module_system = "es-modules"
    dialect = "typescript"
    
