language: node_js
dist: jammy
os: linux
node_js:
- 16
jobs:
  include:
    # ...
    - name: Create release and notify Sentry of deploy
      env: SENTRY_ORG=nathanael-a2 SENTRY_PROJECT=lor-tracker SENTRY_ENVIRONMENT=production
      script: |
        curl -sL https://sentry.io/get-cli/ | bash
        export SENTRY_RELEASE=$(sentry-cli releases propose-version)
        sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
        sentry-cli releases set-commits $SENTRY_RELEASE --auto
        sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps path-to-sourcemaps-if-applicable
        sentry-cli releases finalize $SENTRY_RELEASE
        sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
