# baseURL
@baseURL = http://localhost:3000

###
# Find All Users
GET {{ baseURL }}/users

###
# Find User By username
GET {{ baseURL }}/users/example

###
# Create User
POST {{ baseURL }}/users
Content-Type: application/json

{
  "username": "example2",
  "email": "example2@email.com",
	"password": "password"
}

###
# Modify User By Username
PUT {{ baseURL }}/users/example
Content-Type: application/json

{
    "email": "example@email.com",
	"password": "password2"
}

###
# Delete User By Username
DELETE {{ baseURL }}/users/example
