name: Build and Test
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use for build and test'
        required: false
        default: "testing"
        type: string
    secrets:
      DOPPLER_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 19.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.1
      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-npm
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
      - name: Fetch Doppler Secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          LOG_DIR: ${{ steps.doppler.outputs.LOG_DIR }}
          RIOT_API_KEY: ${{ steps.doppler.outputs.RIOT_API_KEY }}
          DB_HOST: ${{ steps.doppler.outputs.DB_HOST }}
          DB_DATABASE: ${{ steps.doppler.outputs.DB_DATABASE }}
          SECRET_KEY: ${{ steps.doppler.outputs.SECRET_KEY }}
        run: npm run test:ci
      - if: ${{ inputs.environment == "testing" }} 
        name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: ./src/coverage/cobertura-coverage.xml
        
