name: Build and Test
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use for build and test'
        required: false
        default: "testing"
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 19.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.1
      - name: Fetch Doppler Secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
      - run: printenv
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        env:
          LOG_DIR: ${{ steps.doppler.outputs.LOG_DIR }}
          RIOT_API_KEY: ${{ steps.doppler.outputs.RIOT_API_KEY }}
          DB_HOST: ${{ steps.doppler.outputs.DB_HOST }}
          DB_DATABASE: ${{ steps.doppler.outputs.DB_DATABASE }}
          SECRET_KEY: ${{ steps.doppler.outputs.SECRET_KEY }}
        run: npm run test:ci
