name: Upload to CodeCov

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main , develop]

jobs:
  build:
    uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@feature/reusable-workflows
    with:
      environment: testing
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3  

