name: Upload to CodeCov

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main , develop]

jobs:
  build:
    uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@development
    
