name: Upload to CodeCov
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop, feature/*]
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: testing
    secrets: inherit
  report:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
