name: Deepsource Analysis

on:
  push:
    branches: [ feature/*, develop ]
  pull_request:
    branches: [ feature/* , develop, main]

jobs:
  build:
    uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@development
    with:
      environment: testing

  report:
    runs-on: ubuntu-latest
    steps:
     - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
           key: javascript
           coverage-file: ./coverage/cobertura-coverage.xml
           dsn: ${{ secrets.DEEPSOURCE_DSN }}
