name: Deepsource Analysis
on:
  push:
    branches: [feature/*, develop]
  pull_request:
    branches: [feature/*, develop, main]
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: testing
    secrets: inherit
  report:
    runs-on: ubuntu-latest
    environment: testing
    needs: build
    steps:
      - name: Download test artifacts
        uses: actions/download-artifact@v4
        with:
          name: code-coverage-report
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: javascript
          coverage-file: cobertura-coverage.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
