name: Deepsource Analysis

on:
  push:
    branches: [ feature/*, develop ]
  pull_request:
    branches: [ feature/* , develop, main]

jobs:
  run:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 19.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.1
      - name: Install dependencies
        run: npm ci
      - name: Run tests and collect coverage
        env:
          LOG_DIR: ${{ secrets.LOG_DIR }}
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm run test
        continue-on-error: true
      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
            key: javascript
            coverage-file: ./coverage/cobertura-coverage.xml
            dsn: ${{ secrets.DEEPSOURCE_DSN }}
