name: Deepsource Analysis

on:
  push:
    branches: [ feature/*, develop ]
  pull_request:
    branches: [ feature/* , develop, main]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      environment: testing
    secrets: inherit

  report:
    runs-on: ubuntu-latest
    steps:
     - name: Report test coverage to DeepSource
       uses: deepsourcelabs/test-coverage-action@master
       with:
        key: javascript
        coverage-file: ./coverage/cobertura-coverage.xml
        dsn: ${{ secrets.DEEPSOURCE_DSN }}
