name: release

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@development
      with:
          environment: production
    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
      with:
        environment: production
        sourcemaps: './src'


