name: Test Reporter

on:
  push:
   branches:
     - feature/*

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    environment: testing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up node 19.1
        uses: actions/setup-node@v3
        with:
          node-version: 19.1
      - name: Install dependencies
        run: npm ci
      - name: Run tests and collect coverage
        env:
          LOG_DIR: ${{ secrets.LOG_DIR }}
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: npm run test
      - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml


