name: Test Reporter

on:
  push:
   branches:
     - feature/*
     - bugfix/*
     - hotfix/*
     - development

jobs:
  build:
    uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@feature/reusable-workflows
    with:
      environment: testing

  report-test:
    runs-on: ubuntu-latest
    name: Report Tests
    steps:
    - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-report/**/*.xml


