name: Test Reporter

on:
  push:
   branches:
     - feature/*
     - bugfix/*
     - hotfix/*
     - development

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    environment: testing
    steps:
      uses: NathanaelAma/LoRDeckTrackerServer/.github/workflows/build.yml@development
      with:
        environment: testing
    - name: Test Report
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-report/**/*.xml


