name: Test
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to use for build and test'
        required: false
        default: "testing"
        type: string
    secrets:
      DOPPLER_TOKEN:
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Fetch Doppler Secrets
        uses: dopplerhq/secrets-fetch-action@v1.1.3
        id: doppler
        with:
          doppler-token: ${{ secrets.DOPPLER_TOKEN }}
          inject-env-vars: true
      - name: Run tests
        env:
          LOG_DIR: ${{ steps.doppler.outputs.LOG_DIR }}
          RIOT_API_KEY: ${{ steps.doppler.outputs.RIOT_API_KEY }}
          DB_HOST: ${{ steps.doppler.outputs.DB_HOST }}
          DB_DATABASE: ${{ steps.doppler.outputs.DB_DATABASE }}
          SECRET_KEY: ${{ steps.doppler.outputs.SECRET_KEY }}
        run: npm run test:ci
        continue-on-error: true
      - if: ${{ inputs.environment == 'testing' }}
        name: Archive Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/cobertura-coverage.xml
          retention-days: 5
          if-no-files-found: warn
      - if: ${{ inputs.environment == 'testing' }}
        name: Archive Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: junit.xml
          retention-days: 5
          if-no-files-found: warn
